/**
 * Contains utilities for validating {@link com.github.evanquan.parsely.words.Command}s
 * generated by {@link com.github.evanquan.parsely.parser.Parser}s.
 *
 * @author Evan Quan
 */
package com.github.evanquan.parsely.validation;