package com.github.evanquan.parsely.parser;

public enum Condition {
    DIRECT_OBJECT_PHRASE_DOES_NOT_EXIST,
    DIRECT_OBJECT_PHRASE_EXISTS,
    PREPOSITION_DOES_NOT_EXIST,
    PREPOSITION_OBJECT_PHRASE_EXISTS,
    INDIRECT_OBJECT_PHRASE_DOES_NOT_EXIST,
    INDIRECT_OBJECT_PHRASE_EXISTS,
    ANY_OBJECT_PHRASES_EXIST,
    ALWAYS,
}
