package com.github.evanquan.parsely.parser;

public enum Condition {
    IF_DIRECT_OBJECT_PHRASE_DOES_NOT_EXIST,
    IF_DIRECT_OBJECT_PHRASE_EXISTS,
    IF_INDIRECT_OBJECT_PHRASE_DOES_NOT_EXIST,
    IF_INDIRECT_OBJECT_PHRASE_EXISTS,
    IF_ANY_OBJECT_PHRASES_EXIST,
    ALWAYS,
}
